name: Upload Python Package
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Bump Version
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
       curl -s https://pypi.org/pypi/openapi-perf/json | grep -Eo '"version":"[0-9].[0-9][0-9]?.[0-9][0-9]?"' | grep -Eo "[0-9].[0-9][0-9]?.[0-9][0-9]?" > old
       grep -Eo 'VERSION = "[0-9].[0-9][0-9]?.[0-9][0-9]?"' setup.py | grep -Eo "[0-9].[0-9][0-9]?.[0-9][0-9]?" > new

       cat new
       cat old
       if cmp --silent new old; then
        echo --- SKIPPING VERSION BUMP ---
       else
        echo ---BUMPING VERSION---
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload dist/*
       fi